version: 2.1
commands:
  build_and_save:
    description: build stm32
    steps:
      - checkout:
          path: ~/CircleCI
      - run:
          name: Run Build Script
          command: |
            apt-get update
            apt-get install --yes wget
            apt-get install --yes make
            apt-get install --yes build-essential
            chmod +x ./build.sh
            ./build.sh
jobs:
  build_and_save:
    working_directory: ~/CircleCI
    steps:
      - build_and_save
workflows:
  build_and_save:
    jobs:
      - build_and_save
      
