version: 2.1
commands:
  build_and_save:
    description: build stm32
    steps:
      - checkout:
          path: ~/CircleCI
      - run:
          name: Run Build Script
          command: |
            chmod +x ./build.sh
            ./build.sh
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /DIO_Abstraction/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /DIO_Abstraction/artifacts/art-2;
      - store_artifacts:
          path: /DIO_Abstraction/art-1
          destination: artifact-file
      - store_artifacts:
          path: /DIO_Abstraction/artifacts
jobs:
  build_and_save:
    working_directory: ~/CircleCI
    docker:
      - image: nhoklankan7/stm32cubeide
    steps:
      - build_and_save
workflows:
  build_and_save:
    jobs:
      - build_and_save
      
