version: 2.1
commands:
  build_and_save:
    description: build stm32
    steps:
      - checkout:
          path: ~/CircleCI
      - run:
          name: Run Build Script
          command: |
            chmod +x ./build.sh
            ./build.sh
      - store_artifacts:
          path: ~/CircleCI/DIO_Abstraction/build


jobs:
  build_and_save:
    working_directory: ~/CircleCI
    docker:
      - image: nhoklankan7/stm32cubeide
    steps:
      - build_and_save

workflows:
  version: 2
  build_and_save:
    jobs:
      - build_and_save
