version: 2.1
command:
  build_and_save:
    steps:
      -run:
        name: Run Build Script
        command: ./build.sh
jobs:
  build_and_save:
    working_directory: ~/CircleCI
    docker:
      -image: nhoklankan7/stm32cubeide
    steps:
      -build_and_save
workflows:
  build_and_save:
    jobs:
      - build_and_save
      
